default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  database: <%= ENV['PGDATABASE'] || 'security_api' %>
  username: <%= ENV['PGUSER'] || 'postgres' %>
  password: <%= ENV['PGPASSWORD'] || 'postgres' %>
  host: <%= ENV['PGHOST'] || 'db' %>
  port: <%= ENV['PGPORT'] || 5432 %>
  prepared_statements: false

test:
  <<: *default
  database: security_api_test

development:
  <<: *default

production:
  <<: *default
