name: Ruby

on:
  pull_request:
    branches:
      - 'main'
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - '3.1.2'

    services:
      postgres:
        image: postgres:14.2-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo sh -c "echo 'deb https://gitsecret.jfrog.io/artifactory/git-secret-deb git-secret main' >> /etc/apt/sources.list"
          wget -qO - 'https://gitsecret.jfrog.io/artifactory/api/gpg/key/public' | sudo apt-key add -
          sudo apt-get update
          sudo apt-get install -yqq git-secret gpg libpq-dev
          git secret --version

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

#      - name: Import GPG key
#        id: import_gpg
#        uses: crazy-max/ghaction-import-gpg@v4
#        with:
#          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
#          passphrase: ${{ secrets.PASSPHRASE }}

      - name: Reveal secrets
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          PASSPHRASE: ${{ secrets.PASSPHRASE }}
        run: |
          echo "$GPG_PRIVATE_KEY" > ./private_key.gpg
          gpg --batch --yes --pinentry-mode loopback --import private_key.gpg

          echo '>> root: '
          ls
          echo '>> config: '
          ls config
#          git secret cat -p $(echo $PASSPHRASE | sed 's/./& /g')
#          git secret reveal -p $(echo $PASSPHRASE | sed 's/./& /g') -f -F -v
#
          git secret cat -p $PASSPHRASE
          git secret reveal -p $PASSPHRASE -f -F -v

      - name: Build App
        env:
          PGHOST: localhost
          RAILS_ENV: test
        run: bin/rails db:create db:migrate

      - name: Run the default task
        env:
          PGHOST: localhost
        run: bundle exec rake
