name: Ruby

on:
  pull_request:
    branches:
      - 'main'
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - '3.1.2'

    services:
      postgres:
        image: postgres:14.2-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: sudo apt-get install -yqq git-secret gpg libpq-dev

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v4
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          git-user-signingkey: true
          git-commit-gpgsign: true

      - name: Reveal secrets
        env:
          PASSPHRASE: ${{ secrets.PASSPHRASE }}
        run: |
          git secret reveal -p $(echo $PASSPHRASE | sed 's/./& /g')
          echo '>> root: '
          ls
          echo '>> config: '
          ls config

      - name: Build App
        env:
          PGHOST: localhost
          RAILS_ENV: test
        run: bin/rails db:create db:migrate

      - name: Run the default task
        env:
          PGHOST: localhost
        run: bundle exec rake
